# General Configs
[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib'] # Includes node_modules too for any previous imports with npm
test = 'testFoundry'           # "testFoundry" -> foundry test only while "test" -> js test files
cache_path  = 'cache_forge'

# Solidity & EVM Specific Configs
solc = "0.8.20"
optimizer = true
optimizer_runs = 99999
auto_detect_solc = false
emv_version = "paris"
  

# Test Specific Configs
verbosity = 2
gas_reports = [" "]
sender = "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38"


# Formatter Specific Configs
[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

# RPC & Etherscan Config Keys
[etherscan]
  arbitrum_one = { key = "${process.env.ARBISCAN_API}" }
  bnb_smart_chain = { key = "${process.env.BNBSCAN_API}" }
  goerli = { key = "${process.env.ETHERSCAN_API}" }
  mainnet = { key = "${process.env.ETHERSCAN_API}" }
  optimism = { key = "${process.env.OPTIMISM_API}" }
  polygon = { key = "${process.env.POLYGONSCAN_API}" }
  sepolia = { key = "${process.env.ETHERSCAN_API}" }

[rpc_endpoints]
  localhost = "http://localhost:8545"

  #ETH Networks
  mainnet = "https://mainnet.infura.io/v3/${process.env.INFURA_PROJECT_ID}"
  goerli = "https://goerli.infura.io/v3/${process.env.INFURA_PROJECT_ID}"
  sepolia = "https://sepolia.infura.io/v3/${process.env.INFURA_PROJECT_ID}"
  
  # Polygon Networks
  polygon = "https://polygon-rpc.com/"
  polygonMumbai = "https://rpc-mumbai.maticvigil.com/"

  #BNB Networks
  bnb_smart_chain = "https://bsc-dataseed.binance.org"
  bnb_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

  #Optimism Networks
  optimism = "https://mainnet.optimism.io"
  optimismGoerli = "https://goerli.optimism.io"

  #zkEVM Networks
  zkEVMMainnet = "https://zkevm-rpc.com"
  zkEVMTestnet =  "https://rpc.public.zkevm-test.net"